interface SikayetOzellik {
    SirketAdi: string,
    SikayetEdenKullaniciAdi: string,
    SikayetBasligi: string,
    Tarih: string,
    CevapDurumu: boolean,
    Goruntulenme: number,
    SikayetMetni: string,
    SikayetNumarasi: number
}


export const Sikayet: Array<SikayetOzellik> = [
    {
        SirketAdi: "Barçın Outlet",
        SikayetEdenKullaniciAdi: "Ziya Bozlar",
        SikayetBasligi: "Yemek Bozuk",
        Tarih: "25.12.2022",
        CevapDurumu: false,
        Goruntulenme: 5,
        SikayetMetni: "Geçenlerde bir outlet mağazasından bir çift ayakkabı satın aldım ve sadece birkaç giymeden sonra dağılmaya başladıklarını görünce çok hayal kırıklığına uğradım. Ayakkabının tabanı sayadan ayrılmaya, burun kısmındaki dikişler açılmaya başladı. Bu markadan daha iyi kalite bekliyordum ve satın aldığımdan çok mutsuzum. Bu outlet mağazasından alışveriş yapmanızı tavsiye etmem",
        SikayetNumarasi: 1,
    },
    {
        SirketAdi: "Adidas",
        SikayetEdenKullaniciAdi: "Ziya Bozlar",
        SikayetBasligi: "Paramı Vermediler",
        Tarih: "25.12.2022",
        CevapDurumu: false,
        Goruntulenme: 52,
        SikayetMetni: "Geçenlerde bir outlet mağazasından bir çift ayakkabı satın aldım ve sadece birkaç giymeden sonra dağılmaya başladıklarını görünce çok hayal kırıklığına uğradım. Ayakkabının tabanı sayadan ayrılmaya, burun kısmındaki dikişler açılmaya başladı. Bu markadan daha iyi kalite bekliyordum ve satın aldığımdan çok mutsuzum. Bu outlet mağazasından alışveriş yapmanızı tavsiye etmem",
        SikayetNumarasi: 2,
    },
    {
        SirketAdi: "Nike",
        SikayetEdenKullaniciAdi: "Ziya Bozlar",
        SikayetBasligi: "Yırtık Geldi",
        Tarih: "25.12.2022",
        CevapDurumu: true,
        Goruntulenme: 323,
        SikayetMetni: "Geçenlerde bir outlet mağazasından bir çift ayakkabı satın aldım ve sadece birkaç giymeden sonra dağılmaya başladıklarını görünce çok hayal kırıklığına uğradım. Ayakkabının tabanı sayadan ayrılmaya, burun kısmındaki dikişler açılmaya başladı. Bu markadan daha iyi kalite bekliyordum ve satın aldığımdan çok mutsuzum. Bu outlet mağazasından alışveriş yapmanızı tavsiye etmem",
        SikayetNumarasi: 3,
    },
    {
        SirketAdi: "Nike",
        SikayetEdenKullaniciAdi: "Ziya Bozlar",
        SikayetBasligi: "Rengi Yanlış",
        Tarih: "25.12.2022",
        CevapDurumu: true,
        Goruntulenme: 12,
        SikayetMetni: "Geçenlerde bir outlet mağazasından bir çift ayakkabı satın aldım ve sadece birkaç giymeden sonra dağılmaya başladıklarını görünce çok hayal kırıklığına uğradım. Ayakkabının tabanı sayadan ayrılmaya, burun kısmındaki dikişler açılmaya başladı. Bu markadan daha iyi kalite bekliyordum ve satın aldığımdan çok mutsuzum. Bu outlet mağazasından alışveriş yapmanızı tavsiye etmem",
        SikayetNumarasi: 4,
    },
    {
        SirketAdi: "Nike",
        SikayetEdenKullaniciAdi: "Ziya Bozlar",
        SikayetBasligi: "Küçük Numara",
        Tarih: "25.12.2022",
        CevapDurumu: true,
        Goruntulenme: 442,
        SikayetMetni: "Geçenlerde bir outlet mağazasından bir çift ayakkabı satın aldım ve sadece birkaç giymeden sonra dağılmaya başladıklarını görünce çok hayal kırıklığına uğradım. Ayakkabının tabanı sayadan ayrılmaya, burun kısmındaki dikişler açılmaya başladı. Bu markadan daha iyi kalite bekliyordum ve satın aldığımdan çok mutsuzum. Bu outlet mağazasından alışveriş yapmanızı tavsiye etmem",
        SikayetNumarasi: 5,
    },
    {
        SirketAdi: "VANS",
        SikayetEdenKullaniciAdi: "Ziya Bozlar",
        SikayetBasligi: "Ulaşılamıyor",
        Tarih: "25.12.2022",
        CevapDurumu: true,
        Goruntulenme: 123,
        SikayetMetni: "Geçenlerde bir outlet mağazasından bir çift ayakkabı satın aldım ve sadece birkaç giymeden sonra dağılmaya başladıklarını görünce çok hayal kırıklığına uğradım. Ayakkabının tabanı sayadan ayrılmaya, burun kısmındaki dikişler açılmaya başladı. Bu markadan daha iyi kalite bekliyordum ve satın aldığımdan çok mutsuzum. Bu outlet mağazasından alışveriş yapmanızı tavsiye etmem",
        SikayetNumarasi: 6,
    },
    {
        SirketAdi: "Puma",
        SikayetEdenKullaniciAdi: "Ziya Bozlar",
        SikayetBasligi: "Çok Kalitesiz",
        Tarih: "25.12.2022",
        CevapDurumu: true,
        Goruntulenme: 512,
        SikayetMetni: "Geçenlerde bir outlet mağazasından bir çift ayakkabı satın aldım ve sadece birkaç giymeden sonra dağılmaya başladıklarını görünce çok hayal kırıklığına uğradım. Ayakkabının tabanı sayadan ayrılmaya, burun kısmındaki dikişler açılmaya başladı. Bu markadan daha iyi kalite bekliyordum ve satın aldığımdan çok mutsuzum. Bu outlet mağazasından alışveriş yapmanızı tavsiye etmem",
        SikayetNumarasi: 7,
    },

]